<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

class PasswordResetMailable extends Mailable
{
    use Queueable, SerializesModels;

    public string $resetUrl; // Property to hold the frontend reset URL
    public string $userName; // Optional: To personalize the email (e.g., "Hello, [User Name]")
    public int $expireMinutes; // Optional: To show expiration time
    /**
     * Create a new message instance.
     *
     * @param string $resetToken The password reset token generated by Laravel
     * @param string $userEmail The email of the user requesting the reset
     * @param string $userName (Optional) The user's name, if available
     * @return void
     */
    public function __construct(string $resetToken, string $userEmail, ?string $userName = null)
    {
        // Construct the frontend reset URL
        // Ensure config('app.frontend_url') is set in .env and config/app.php
        $this->resetUrl = config('app.frontend_url') . '/reset-password?token=' . $resetToken . '&email=' . urlencode($userEmail);
        $this->userName = $userName ?? 'User'; // Default to 'User' if name is not provided
        $this->expireMinutes = config('auth.passwords.users.expire'); // Get expiry from config
    }

    /**
     * Get the message envelope.
     */
    public function envelope(): Envelope
    {
        return new Envelope(
            subject: 'Reset Your Password - ' . config('app.name'), // Dynamic subject
        );
    }

    /**
     * Get the message content definition.
     */
    public function content(): Content
    {
        // return new Content(
        //     view: 'view.name',
        // );
        return new Content(
            // markdown: 'emails.password-reset', // Use a Blade Markdown view
            view: 'emails.custom-password-reset',
            with: [
                'resetUrl' => $this->resetUrl,
                'userName' => $this->userName,
                'expireMinutes' => $this->expireMinutes,
            ]
        );
    }

    /**
     * Get the attachments for the message.
     *
     * @return array<int, \Illuminate\Mail\Mailables\Attachment>
     */
    public function attachments(): array
    {
        return [];
    }
}
