<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;
use App\Models\User;

class PasswordResetSuccessMailable extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;

    public $fullname;
    public $url;
    /**
     * Create a new message instance.
     *
     * @param string $resetToken The password reset token generated by Laravel
     * @param string $userEmail The email of the user requesting the reset
     * @param string $userName (Optional) The user's name, if available
     * @return void
     */
    public function __construct(string $fullname, string $url)
    {
        $this->fullname = $fullname;
        $this->url = $url;
    }

    /**
     * Get the message envelope.
     */
    public function envelope(): Envelope
    {
        return new Envelope(
            subject: 'Password Change Confirmation - ' . config('app.name'), // Dynamic subject
        );
    }

    /**
     * Get the message content definition.
     */
    public function content(): Content
    {
        return new Content(
            view: 'emails.custom-password-reset-success',
            with: [
                'url' => url($this->url),
                'fullname' => $this->fullname,
            ]
        );
    }

    /**
     * Get the attachments for the message.
     *
     * @return array<int, \Illuminate\Mail\Mailables\Attachment>
     */
    public function attachments(): array
    {
        return [];
    }
}
